<?php
$this->title = "My Albums";
$this->headTitle($this->title);
?>
<p>
    <a href="<?php echo $this->url(array(
            'controller' => 'Index',
            'action' => 'add',
        ));?>">Add new album</a>
</p>
<table>
    <tr>
        <th>Nº</th>
        <th>Artist</th>
        <th>Title</th>
        <th>Actions</th>
    </tr>
<?php
$n = 1;
foreach ($this->albums as $album) {
?>
    <tr>
        <td><a href="<?php echo $this->url(array(
                    'controller' => 'Index',
                    'action' => 'show',
                    'id' => $album->id,
                ));?>"><?php echo $n; ?></a></td>
        <td><?php echo $this->escape($album->artist); ?></td>
        <td><?php echo $this->escape($album->title); ?></td>
        <td>
            <a href="<?php echo $this->url(array(
                    'controller' => 'Index',
                    'action' => 'edit',
                    'id' => $album->id,
                ));?>">Edit</a>
            <a href="<?php echo $this->url(array(
                    'controller' => 'Index',
                    'action' => 'delete',
                    'id' => $album->id,
                ));?>">Delete</a>
        </td>
    </tr>
<?php
    $n++;
}
?>
</table>